# Task 1:

## Q 1

In [1]:
def cal():
    return 5/0
try:
    print('Yeah ! you answer is: ',cal())
except ZeroDivisionError as Z:
    print(Z,' Sorry!..you are not divisible by zero')
except:
    print('Invalid divider')

division by zero  Sorry!..you are not divisible by zero


## Q 2

In [2]:
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 

In [3]:
sent = [(sub+" "+verb+" "+ob) for sub in subjects for verb in verbs for ob in objects]
for s in sent:
    print(s)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:

## Q1

In [12]:
#vector
vec = np.array([5,6,7,8])
N = 3
vec

array([5, 6, 7, 8])

In [24]:
ls = []
def func(v,n):
    for i in range(n):
        ls.append(vec**(N-1-i))
        
    return np.column_stack(ls)
    print(ls)
    #print(np.column_stack(ls))
        
mat = func(vec,N)

In [25]:
print(mat)

[[25  5  1]
 [36  6  1]
 [49  7  1]
 [64  8  1]]
