# Q 1

In [6]:
#Solution No 1
import numpy as np

x = np.array([1,2,3,4])
power_x = np.vander(x)
print(power_x)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [34]:
#solution NO 2
def vendor(ipvec, n, increasing):
    if not increasing:
        pow_ip = np.array([x**(N-i-1) for x in ipvec for i in range(n)]).reshape(ipvec.size,n)
    elif increasing:
        pow_ip = np.array([x**i for x in ipvec for i in range(n)]).reshape(ipvec.size,n)
    return pow_ip

ipvec = np.array([1,2,3,4])
no_col = 4
power_of_input_vector = vendor(ipvec,no_col, False)
print(power_of_input_vector)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [35]:
vendor(ipvec,no_col, True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

# Q 2

In [109]:
def moving_Avg(ls,n=3):
    csum = np.cumsum(ls,dtype=float)
    csum[n:] = csum[n:] - csum[:-n]
    return csum[n-1:]/n    
    
ls = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
moving_Avg(ls).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])

In [108]:
moving_Avg(ls,n=4)  # for 4 window base avarage...

array([  4.25,   5.5 ,   6.75,   7.75,  23.5 ,  39.5 ,  57.25,  79.25,
        88.  , 107.5 ])