# Q1

In [7]:
import numpy as np
vec = np.array([1,2,3,4])
N = 4
ls = []
def func(v,n):
    for i in range(n):
        ls.append(vec**(N-1-i)) 
    return np.column_stack(ls)
        
mat = func(vec,N)
print(mat)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


# Q2

In [20]:
def moving_Avg(ls,n):
    csum = np.cumsum(ls,dtype=float)
    csum[n:] = csum[n:] - csum[:-n]
    return csum[n-1:]/n    

window =3
ls = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
print('List :',ls)
print('\nMoving average based on 3 window size:')
print(moving_Avg(ls,window).round(2))

List : [  3   5   7   2   8  10  11  65  72  81  99 100 150]

Moving average based on 3 window size:
[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
